FROM python:3.11-slim

WORKDIR /srv
COPY requirements.txt /srv/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# copy app
COPY app /srv/app

# tạo nơi lưu data (bots, state.json)
RUN mkdir -p /data
VOLUME ["/data"]

ENV PYTHONUNBUFFERED=1
EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
